# Generated by Django 4.2.2 on 2023-07-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=250)),
                ('pimg', models.ImageField(upload_to='pics')),
                ('details', models.TextField()),
            ],
        ),
    ]
